Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "shell", inline: <<-SHELL
	  sudo apt-get update
	  apt-get install -y build-essential python wget

	  #https://github.com/nodesource/distributionss
	  curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
	  sudo apt-get install -y nodejs

	  cd /vagrant
	  sudo npm install --no-bin-links
	  sudo npm install -g gulp

  SHELL

  config.vm.provision "shell", run:"always", privileged:false, inline: <<-SHELL
	  cd /vagrant
	  sudo npm install --no-bin-links
	  sudo gulp
  SHELL

end
